#!/usr/bin/env bash
# Script that displays information about subdomains (record type and destination IP)

if [ "$#" -lt 1 ]; then
    exit 1
fi

DOMAIN=$1

if [ "$#" -eq 2 ]; then
    sub=$2
    record_info=$(dig +noall +answer ${sub}.${DOMAIN} | grep -v '^;' | grep A)
    if [ -n "$record_info" ]; then
        echo "$record_info" | while read -r line; do
            record_type=$(echo "$line" | awk '{print $(NF-1)}')
            destination=$(echo "$line" | awk '{print $NF}')
            if [ -n "$destination" ]; then
                echo "The subdomain ${sub} is a ${record_type} record and points to ${destination}"
                break
            fi
        done
    fi
else
    for sub in www lb-01 web-01 web-02; do
        record_info=$(dig +noall +answer ${sub}.${DOMAIN} | grep -v '^;' | grep A)
        if [ -n "$record_info" ]; then
            echo "$record_info" | while read -r line; do
                record_type=$(echo "$line" | awk '{print $(NF-1)}')
                destination=$(echo "$line" | awk '{print $NF}')
                if [ -n "$destination" ]; then
                    echo "The subdomain ${sub} is a ${record_type} record and points to ${destination}"
                    break
                fi
            done
        fi
    done
fi
