#!/usr/bin/env bash
# Displays information about DNS records for subdomains

domain=$1
subdomain=$2

print_record() {
    sub=$1
    ip=$(dig "$sub.$domain" +short | head -n 1)
    echo "The subdomain $sub is a A record and points to $ip"
}

if [ -z "$subdomain" ]; then
    print_record www
    print_record lb-01
    print_record web-01
    print_record web-02
else
    print_record "$subdomain"
fi
