#!/usr/bin/env bash
# Displays DNS record information for subdomains

domain=$1
subdomain=$2

show_record() {
    sub=$1
    result=$(dig "$sub.$domain" +short | head -n 1)

    if [ -n "$result" ]; then
        echo "The subdomain $sub is a A record and points to $result"
    fi
}

if [ -z "$subdomain" ]; then
    show_record www
    show_record lb-01
    show_record web-01
    show_record web-02
else
    show_record "$subdomain"
fi
